// 2026 FIFA World Cup 数据
const WC2026 = {
  tournament: {
    name: 'FIFA World Cup 2026™',
    hosts: ['美国', '加拿大', '墨西哥'],
    startDate: '2026-06-11',
    endDate: '2026-07-19',
    teams: 48,
    venues: 16,
    totalMatches: 104,
  },

  groups: {
    A: { name: 'A组', teams: ['墨西哥', '韩国', '捷克', '南非'] },
    B: { name: 'B组', teams: ['瑞士', '加拿大', '卡塔尔', '波黑'] },
    C: { name: 'C组', teams: ['苏格兰', '摩洛哥', '巴西', '海地'] },
    D: { name: 'D组', teams: ['美国', '澳大利亚', '土耳其', '巴拉圭'] },
    E: { name: 'E组', teams: ['德国', '科特迪瓦', '厄瓜多尔', '库拉索'] },
    F: { name: 'F组', teams: ['瑞典', '日本', '荷兰', '突尼斯'] },
    G: { name: 'G组', teams: ['新西兰', '伊朗', '比利时', '埃及'] },
    H: { name: 'H组', teams: ['乌拉圭', '沙特', '西班牙', '佛得角'] },
    I: { name: 'I组', teams: ['挪威', '法国', '塞内加尔', '伊拉克'] },
    J: { name: 'J组', teams: ['阿根廷', '奥地利', '约旦', '阿尔及利亚'] },
    K: { name: 'K组', teams: ['哥伦比亚', '刚果(金)', '葡萄牙', '乌兹别克斯坦'] },
    L: { name: 'L组', teams: ['英格兰', '加纳', '巴拿马', '克罗地亚'] },
  },

  standings: {
    A: [
      { team: '墨西哥', flag: '🇲🇽', p: 1, w: 1, d: 0, l: 0, gf: 2, ga: 0, gd: 2, pts: 3 },
      { team: '韩国', flag: '🇰🇷', p: 1, w: 1, d: 0, l: 0, gf: 2, ga: 1, gd: 1, pts: 3 },
      { team: '捷克', flag: '🇨🇿', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 2, gd: -1, pts: 0 },
      { team: '南非', flag: '🇿🇦', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 2, gd: -2, pts: 0 },
    ],
    B: [
      { team: '瑞士', flag: '🇨🇭', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '加拿大', flag: '🇨🇦', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '卡塔尔', flag: '🇶🇦', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '波黑', flag: '🇧🇦', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
    ],
    C: [
      { team: '苏格兰', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', p: 1, w: 1, d: 0, l: 0, gf: 1, ga: 0, gd: 1, pts: 3 },
      { team: '摩洛哥', flag: '🇲🇦', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '巴西', flag: '🇧🇷', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '海地', flag: '🇭🇹', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 1, gd: -1, pts: 0 },
    ],
    D: [
      { team: '美国', flag: '🇺🇸', p: 1, w: 1, d: 0, l: 0, gf: 4, ga: 1, gd: 3, pts: 3 },
      { team: '澳大利亚', flag: '🇦🇺', p: 1, w: 1, d: 0, l: 0, gf: 2, ga: 0, gd: 2, pts: 3 },
      { team: '土耳其', flag: '🇹🇷', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 2, gd: -2, pts: 0 },
      { team: '巴拉圭', flag: '🇵🇾', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 4, gd: -3, pts: 0 },
    ],
    E: [
      { team: '德国', flag: '🇩🇪', p: 1, w: 1, d: 0, l: 0, gf: 7, ga: 1, gd: 6, pts: 3 },
      { team: '科特迪瓦', flag: '🇨🇮', p: 1, w: 1, d: 0, l: 0, gf: 1, ga: 0, gd: 1, pts: 3 },
      { team: '厄瓜多尔', flag: '🇪🇨', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 1, gd: -1, pts: 0 },
      { team: '库拉索', flag: '🇨🇼', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 7, gd: -6, pts: 0 },
    ],
    F: [
      { team: '瑞典', flag: '🇸🇪', p: 1, w: 1, d: 0, l: 0, gf: 5, ga: 1, gd: 4, pts: 3 },
      { team: '日本', flag: '🇯🇵', p: 1, w: 0, d: 1, l: 0, gf: 2, ga: 2, gd: 0, pts: 1 },
      { team: '荷兰', flag: '🇳🇱', p: 1, w: 0, d: 1, l: 0, gf: 2, ga: 2, gd: 0, pts: 1 },
      { team: '突尼斯', flag: '🇹🇳', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 5, gd: -4, pts: 0 },
    ],
    G: [
      { team: '新西兰', flag: '🇳🇿', p: 1, w: 0, d: 1, l: 0, gf: 2, ga: 2, gd: 0, pts: 1 },
      { team: '伊朗', flag: '🇮🇷', p: 1, w: 0, d: 1, l: 0, gf: 2, ga: 2, gd: 0, pts: 1 },
      { team: '比利时', flag: '🇧🇪', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '埃及', flag: '🇪🇬', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
    ],
    H: [
      { team: '乌拉圭', flag: '🇺🇾', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '沙特', flag: '🇸🇦', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '西班牙', flag: '🇪🇸', p: 1, w: 0, d: 1, l: 0, gf: 0, ga: 0, gd: 0, pts: 1 },
      { team: '佛得角', flag: '🇨🇻', p: 1, w: 0, d: 1, l: 0, gf: 0, ga: 0, gd: 0, pts: 1 },
    ],
    I: [
      { team: '挪威', flag: '🇳🇴', p: 1, w: 1, d: 0, l: 0, gf: 4, ga: 1, gd: 3, pts: 3 },
      { team: '法国', flag: '🇫🇷', p: 1, w: 1, d: 0, l: 0, gf: 3, ga: 1, gd: 2, pts: 3 },
      { team: '塞内加尔', flag: '🇸🇳', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 3, gd: -2, pts: 0 },
      { team: '伊拉克', flag: '🇮🇶', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 4, gd: -3, pts: 0 },
    ],
    J: [
      { team: '阿根廷', flag: '🇦🇷', p: 1, w: 1, d: 0, l: 0, gf: 3, ga: 0, gd: 3, pts: 3 },
      { team: '奥地利', flag: '🇦🇹', p: 1, w: 1, d: 0, l: 0, gf: 2, ga: 0, gd: 2, pts: 3 },
      { team: '约旦', flag: '🇯🇴', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 2, gd: -2, pts: 0 },
      { team: '阿尔及利亚', flag: '🇩🇿', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 3, gd: -3, pts: 0 },
    ],
    K: [
      { team: '哥伦比亚', flag: '🇨🇴', p: 1, w: 1, d: 0, l: 0, gf: 3, ga: 1, gd: 2, pts: 3 },
      { team: '刚果(金)', flag: '🇨🇩', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '葡萄牙', flag: '🇵🇹', p: 1, w: 0, d: 1, l: 0, gf: 1, ga: 1, gd: 0, pts: 1 },
      { team: '乌兹别克斯坦', flag: '🇺🇿', p: 1, w: 0, d: 0, l: 1, gf: 1, ga: 3, gd: -2, pts: 0 },
    ],
    L: [
      { team: '英格兰', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', p: 1, w: 1, d: 0, l: 0, gf: 4, ga: 2, gd: 2, pts: 3 },
      { team: '加纳', flag: '🇬🇭', p: 1, w: 1, d: 0, l: 0, gf: 1, ga: 0, gd: 1, pts: 3 },
      { team: '巴拿马', flag: '🇵🇦', p: 1, w: 0, d: 0, l: 1, gf: 0, ga: 1, gd: -1, pts: 0 },
      { team: '克罗地亚', flag: '🇭🇷', p: 1, w: 0, d: 0, l: 1, gf: 2, ga: 4, gd: -2, pts: 0 },
    ],
  },

  scorers: [
    { rank: 1, player: '梅西', team: '阿根廷', flag: '🇦🇷', goals: 3, assists: 0, minutes: 90 },
    { rank: 2, player: '凯恩', team: '英格兰', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', goals: 2, assists: 1, minutes: 90 },
    { rank: 2, player: '姆巴佩', team: '法国', flag: '🇫🇷', goals: 2, assists: 0, minutes: 90 },
    { rank: 2, player: '哈兰德', team: '挪威', flag: '🇳🇴', goals: 2, assists: 0, minutes: 90 },
    { rank: 2, player: '哈弗茨', team: '德国', flag: '🇩🇪', goals: 2, assists: 0, minutes: 90 },
    { rank: 2, player: '巴洛贡', team: '美国', flag: '🇺🇸', goals: 2, assists: 0, minutes: 77 },
    { rank: 2, player: '阿亚里', team: '瑞典', flag: '🇸🇪', goals: 2, assists: 0, minutes: 90 },
    { rank: 8, player: '维尼修斯', team: '巴西', flag: '🇧🇷', goals: 1, assists: 0, minutes: 90 },
    { rank: 8, player: '贝林厄姆', team: '英格兰', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', goals: 1, assists: 1, minutes: 90 },
    { rank: 8, player: '迪亚斯', team: '哥伦比亚', flag: '🇨🇴', goals: 1, assists: 1, minutes: 90 },
    { rank: 8, player: '穆西亚拉', team: '德国', flag: '🇩🇪', goals: 1, assists: 2, minutes: 85 },
    { rank: 8, player: '希门尼斯', team: '墨西哥', flag: '🇲🇽', goals: 1, assists: 0, minutes: 79 },
  ],

  matches: [
    { id: 1, date: '2026-06-12', time: '03:00', timeET: '15:00 ET', group: 'A', home: '墨西哥', homeFlag: '🇲🇽', away: '南非', awayFlag: '🇿🇦', venue: '墨西哥城', status: 'finished', score: [2, 0] },
    { id: 2, date: '2026-06-12', time: '10:00', timeET: '22:00 ET', group: 'A', home: '韩国', homeFlag: '🇰🇷', away: '捷克', awayFlag: '🇨🇿', venue: '瓜达拉哈拉', status: 'finished', score: [2, 1] },
    { id: 3, date: '2026-06-13', time: '03:00', timeET: '15:00 ET', group: 'B', home: '加拿大', homeFlag: '🇨🇦', away: '波黑', awayFlag: '🇧🇦', venue: '多伦多', status: 'finished', score: [1, 1] },
    { id: 4, date: '2026-06-13', time: '09:00', timeET: '21:00 ET', group: 'D', home: '美国', homeFlag: '🇺🇸', away: '巴拉圭', awayFlag: '🇵🇾', venue: '洛杉矶', status: 'finished', score: [4, 1] },
    { id: 5, date: '2026-06-14', time: '09:00', timeET: '21:00 ET', group: 'C', home: '海地', homeFlag: '🇭🇹', away: '苏格兰', awayFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', venue: '波士顿', status: 'finished', score: [0, 1] },
    { id: 6, date: '2026-06-14', time: '12:00', timeET: '00:00 ET', group: 'D', home: '澳大利亚', homeFlag: '🇦🇺', away: '土耳其', awayFlag: '🇹🇷', venue: '温哥华', status: 'finished', score: [2, 0] },
    { id: 7, date: '2026-06-14', time: '06:00', timeET: '18:00 ET', group: 'C', home: '巴西', homeFlag: '🇧🇷', away: '摩洛哥', awayFlag: '🇲🇦', venue: '纽约/新泽西', status: 'finished', score: [1, 1] },
    { id: 8, date: '2026-06-14', time: '03:00', timeET: '15:00 ET', group: 'B', home: '卡塔尔', homeFlag: '🇶🇦', away: '瑞士', awayFlag: '🇨🇭', venue: '旧金山湾区', status: 'finished', score: [1, 1] },
    { id: 9, date: '2026-06-15', time: '07:00', timeET: '19:00 ET', group: 'E', home: '科特迪瓦', homeFlag: '🇨🇮', away: '厄瓜多尔', awayFlag: '🇪🇨', venue: '费城', status: 'finished', score: [1, 0] },
    { id: 10, date: '2026-06-15', time: '01:00', timeET: '13:00 ET', group: 'E', home: '德国', homeFlag: '🇩🇪', away: '库拉索', awayFlag: '🇨🇼', venue: '休斯顿', status: 'finished', score: [7, 1] },
    { id: 11, date: '2026-06-15', time: '04:00', timeET: '16:00 ET', group: 'F', home: '荷兰', homeFlag: '🇳🇱', away: '日本', awayFlag: '🇯🇵', venue: '达拉斯', status: 'finished', score: [2, 2] },
    { id: 12, date: '2026-06-15', time: '10:00', timeET: '22:00 ET', group: 'F', home: '瑞典', homeFlag: '🇸🇪', away: '突尼斯', awayFlag: '🇹🇳', venue: '蒙特雷', status: 'finished', score: [5, 1] },
    { id: 13, date: '2026-06-16', time: '06:00', timeET: '18:00 ET', group: 'H', home: '沙特', homeFlag: '🇸🇦', away: '乌拉圭', awayFlag: '🇺🇾', venue: '迈阿密', status: 'finished', score: [1, 1] },
    { id: 14, date: '2026-06-16', time: '00:00', timeET: '12:00 ET', group: 'H', home: '西班牙', homeFlag: '🇪🇸', away: '佛得角', awayFlag: '🇨🇻', venue: '亚特兰大', status: 'finished', score: [0, 0] },
    { id: 15, date: '2026-06-16', time: '09:00', timeET: '21:00 ET', group: 'G', home: '伊朗', homeFlag: '🇮🇷', away: '新西兰', awayFlag: '🇳🇿', venue: '洛杉矶', status: 'finished', score: [2, 2] },
    { id: 16, date: '2026-06-16', time: '03:00', timeET: '15:00 ET', group: 'G', home: '比利时', homeFlag: '🇧🇪', away: '埃及', awayFlag: '🇪🇬', venue: '西雅图', status: 'finished', score: [1, 1] },
    { id: 17, date: '2026-06-17', time: '03:00', timeET: '15:00 ET', group: 'I', home: '法国', homeFlag: '🇫🇷', away: '塞内加尔', awayFlag: '🇸🇳', venue: '纽约/新泽西', status: 'finished', score: [3, 1] },
    { id: 18, date: '2026-06-17', time: '06:00', timeET: '18:00 ET', group: 'I', home: '伊拉克', homeFlag: '🇮🇶', away: '挪威', awayFlag: '🇳🇴', venue: '波士顿', status: 'finished', score: [1, 4] },
    { id: 19, date: '2026-06-17', time: '09:00', timeET: '21:00 ET', group: 'J', home: '阿根廷', homeFlag: '🇦🇷', away: '阿尔及利亚', awayFlag: '🇩🇿', venue: '堪萨斯城', status: 'finished', score: [3, 0] },
    { id: 20, date: '2026-06-17', time: '12:00', timeET: '00:00 ET', group: 'J', home: '奥地利', homeFlag: '🇦🇹', away: '约旦', awayFlag: '🇯🇴', venue: '旧金山湾区', status: 'finished', score: [2, 0] },
    { id: 21, date: '2026-06-18', time: '07:00', timeET: '19:00 ET', group: 'L', home: '加纳', homeFlag: '🇬🇭', away: '巴拿马', awayFlag: '🇵🇦', venue: '多伦多', status: 'finished', score: [1, 0] },
    { id: 22, date: '2026-06-18', time: '04:00', timeET: '16:00 ET', group: 'L', home: '英格兰', homeFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', away: '克罗地亚', awayFlag: '🇭🇷', venue: '达拉斯', status: 'finished', score: [4, 2] },
    { id: 23, date: '2026-06-18', time: '01:00', timeET: '13:00 ET', group: 'K', home: '葡萄牙', homeFlag: '🇵🇹', away: '刚果(金)', awayFlag: '🇨🇩', venue: '休斯顿', status: 'finished', score: [1, 1] },
    { id: 24, date: '2026-06-18', time: '10:00', timeET: '22:00 ET', group: 'K', home: '乌兹别克斯坦', homeFlag: '🇺🇿', away: '哥伦比亚', awayFlag: '🇨🇴', venue: '墨西哥城', status: 'finished', score: [1, 3] },
    { id: 25, date: '2026-06-19', time: '00:00', timeET: '12:00 ET', group: 'A', home: '捷克', homeFlag: '🇨🇿', away: '南非', awayFlag: '🇿🇦', venue: '亚特兰大', status: 'finished', score: [2, 1] },
    { id: 26, date: '2026-06-19', time: '03:00', timeET: '15:00 ET', group: 'B', home: '瑞士', homeFlag: '🇨🇭', away: '波黑', awayFlag: '🇧🇦', venue: '洛杉矶', status: 'finished', score: [1, 0] },
    { id: 27, date: '2026-06-19', time: '06:00', timeET: '18:00 ET', group: 'B', home: '加拿大', homeFlag: '🇨🇦', away: '卡塔尔', awayFlag: '🇶🇦', venue: '温哥华', status: 'finished', score: [2, 1] },
    { id: 28, date: '2026-06-19', time: '09:00', timeET: '21:00 ET', group: 'A', home: '墨西哥', homeFlag: '🇲🇽', away: '韩国', awayFlag: '🇰🇷', venue: '瓜达拉哈拉', status: 'finished', score: [1, 1] },
    { id: 29, date: '2026-06-20', time: '09:00', timeET: '21:00 ET', group: 'C', home: '巴西', homeFlag: '🇧🇷', away: '海地', awayFlag: '🇭🇹', venue: '费城', status: 'upcoming', score: null },
    { id: 30, date: '2026-06-20', time: '06:00', timeET: '18:00 ET', group: 'C', home: '苏格兰', homeFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', away: '摩洛哥', awayFlag: '🇲🇦', venue: '波士顿', status: 'upcoming', score: null },
    { id: 31, date: '2026-06-20', time: '11:00', timeET: '23:00 ET', group: 'D', home: '土耳其', homeFlag: '🇹🇷', away: '巴拉圭', awayFlag: '🇵🇾', venue: '旧金山湾区', status: 'upcoming', score: null },
    { id: 32, date: '2026-06-20', time: '03:00', timeET: '15:00 ET', group: 'D', home: '美国', homeFlag: '🇺🇸', away: '澳大利亚', awayFlag: '🇦🇺', venue: '西雅图', status: 'upcoming', score: null },
    { id: 33, date: '2026-06-21', time: '04:00', timeET: '16:00 ET', group: 'E', home: '德国', homeFlag: '🇩🇪', away: '科特迪瓦', awayFlag: '🇨🇮', venue: '多伦多', status: 'upcoming', score: null },
    { id: 34, date: '2026-06-21', time: '08:00', timeET: '20:00 ET', group: 'E', home: '厄瓜多尔', homeFlag: '🇪🇨', away: '库拉索', awayFlag: '🇨🇼', venue: '堪萨斯城', status: 'upcoming', score: null },
    { id: 35, date: '2026-06-21', time: '01:00', timeET: '13:00 ET', group: 'F', home: '荷兰', homeFlag: '🇳🇱', away: '瑞典', awayFlag: '🇸🇪', venue: '休斯顿', status: 'upcoming', score: null },
    { id: 36, date: '2026-06-21', time: '12:00', timeET: '00:00 ET', group: 'F', home: '突尼斯', homeFlag: '🇹🇳', away: '日本', awayFlag: '🇯🇵', venue: '蒙特雷', status: 'upcoming', score: null },
    { id: 37, date: '2026-06-22', time: '06:00', timeET: '18:00 ET', group: 'H', home: '乌拉圭', homeFlag: '🇺🇾', away: '佛得角', awayFlag: '🇨🇻', venue: '迈阿密', status: 'upcoming', score: null },
    { id: 38, date: '2026-06-22', time: '00:00', timeET: '12:00 ET', group: 'H', home: '西班牙', homeFlag: '🇪🇸', away: '沙特', awayFlag: '🇸🇦', venue: '亚特兰大', status: 'upcoming', score: null },
    { id: 39, date: '2026-06-22', time: '03:00', timeET: '15:00 ET', group: 'G', home: '比利时', homeFlag: '🇧🇪', away: '伊朗', awayFlag: '🇮🇷', venue: '洛杉矶', status: 'upcoming', score: null },
    { id: 40, date: '2026-06-22', time: '09:00', timeET: '21:00 ET', group: 'G', home: '新西兰', homeFlag: '🇳🇿', away: '埃及', awayFlag: '🇪🇬', venue: '温哥华', status: 'upcoming', score: null },
    { id: 41, date: '2026-06-23', time: '08:00', timeET: '20:00 ET', group: 'I', home: '挪威', homeFlag: '🇳🇴', away: '塞内加尔', awayFlag: '🇸🇳', venue: '纽约/新泽西', status: 'upcoming', score: null },
    { id: 42, date: '2026-06-23', time: '05:00', timeET: '17:00 ET', group: 'I', home: '法国', homeFlag: '🇫🇷', away: '伊拉克', awayFlag: '🇮🇶', venue: '费城', status: 'upcoming', score: null },
    { id: 43, date: '2026-06-23', time: '01:00', timeET: '13:00 ET', group: 'J', home: '阿根廷', homeFlag: '🇦🇷', away: '奥地利', awayFlag: '🇦🇹', venue: '达拉斯', status: 'upcoming', score: null },
    { id: 44, date: '2026-06-23', time: '11:00', timeET: '23:00 ET', group: 'J', home: '约旦', homeFlag: '🇯🇴', away: '阿尔及利亚', awayFlag: '🇩🇿', venue: '旧金山湾区', status: 'upcoming', score: null },
    { id: 45, date: '2026-06-24', time: '04:00', timeET: '16:00 ET', group: 'L', home: '英格兰', homeFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', away: '加纳', awayFlag: '🇬🇭', venue: '波士顿', status: 'upcoming', score: null },
    { id: 46, date: '2026-06-24', time: '07:00', timeET: '19:00 ET', group: 'L', home: '巴拿马', homeFlag: '🇵🇦', away: '克罗地亚', awayFlag: '🇭🇷', venue: '多伦多', status: 'upcoming', score: null },
    { id: 47, date: '2026-06-24', time: '01:00', timeET: '13:00 ET', group: 'K', home: '葡萄牙', homeFlag: '🇵🇹', away: '乌兹别克斯坦', awayFlag: '🇺🇿', venue: '休斯顿', status: 'upcoming', score: null },
    { id: 48, date: '2026-06-24', time: '10:00', timeET: '22:00 ET', group: 'K', home: '哥伦比亚', homeFlag: '🇨🇴', away: '刚果(金)', awayFlag: '🇨🇩', venue: '瓜达拉哈拉', status: 'upcoming', score: null },
    { id: 49, date: '2026-06-25', time: '06:00', timeET: '18:00 ET', group: 'C', home: '苏格兰', homeFlag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', away: '巴西', awayFlag: '🇧🇷', venue: '迈阿密', status: 'upcoming', score: null },
    { id: 50, date: '2026-06-25', time: '06:00', timeET: '18:00 ET', group: 'C', home: '摩洛哥', homeFlag: '🇲🇦', away: '海地', awayFlag: '🇭🇹', venue: '亚特兰大', status: 'upcoming', score: null },
    { id: 51, date: '2026-06-25', time: '03:00', timeET: '15:00 ET', group: 'B', home: '瑞士', homeFlag: '🇨🇭', away: '加拿大', awayFlag: '🇨🇦', venue: '温哥华', status: 'upcoming', score: null },
    { id: 52, date: '2026-06-25', time: '03:00', timeET: '15:00 ET', group: 'B', home: '波黑', homeFlag: '🇧🇦', away: '卡塔尔', awayFlag: '🇶🇦', venue: '西雅图', status: 'upcoming', score: null },
    { id: 53, date: '2026-06-25', time: '09:00', timeET: '21:00 ET', group: 'A', home: '捷克', homeFlag: '🇨🇿', away: '墨西哥', awayFlag: '🇲🇽', venue: '墨西哥城', status: 'upcoming', score: null },
    { id: 54, date: '2026-06-25', time: '09:00', timeET: '21:00 ET', group: 'A', home: '南非', homeFlag: '🇿🇦', away: '韩国', awayFlag: '🇰🇷', venue: '蒙特雷', status: 'upcoming', score: null },
    { id: 55, date: '2026-06-26', time: '04:00', timeET: '16:00 ET', group: 'E', home: '库拉索', homeFlag: '🇨🇼', away: '科特迪瓦', awayFlag: '🇨🇮', venue: '费城', status: 'upcoming', score: null },
    { id: 56, date: '2026-06-26', time: '04:00', timeET: '16:00 ET', group: 'E', home: '厄瓜多尔', homeFlag: '🇪🇨', away: '德国', awayFlag: '🇩🇪', venue: '纽约/新泽西', status: 'upcoming', score: null },
    { id: 57, date: '2026-06-26', time: '07:00', timeET: '19:00 ET', group: 'F', home: '日本', homeFlag: '🇯🇵', away: '瑞典', awayFlag: '🇸🇪', venue: '达拉斯', status: 'upcoming', score: null },
    { id: 58, date: '2026-06-26', time: '07:00', timeET: '19:00 ET', group: 'F', home: '突尼斯', homeFlag: '🇹🇳', away: '荷兰', awayFlag: '🇳🇱', venue: '堪萨斯城', status: 'upcoming', score: null },
    { id: 59, date: '2026-06-26', time: '10:00', timeET: '22:00 ET', group: 'D', home: '土耳其', homeFlag: '🇹🇷', away: '美国', awayFlag: '🇺🇸', venue: '洛杉矶', status: 'upcoming', score: null },
    { id: 60, date: '2026-06-26', time: '10:00', timeET: '22:00 ET', group: 'D', home: '巴拉圭', homeFlag: '🇵🇾', away: '澳大利亚', awayFlag: '🇦🇺', venue: '旧金山湾区', status: 'upcoming', score: null },
    { id: 61, date: '2026-06-27', time: '03:00', timeET: '15:00 ET', group: 'I', home: '挪威', homeFlag: '🇳🇴', away: '法国', awayFlag: '🇫🇷', venue: '波士顿', status: 'upcoming', score: null },
    { id: 62, date: '2026-06-27', time: '03:00', timeET: '15:00 ET', group: 'I', home: '塞内加尔', homeFlag: '🇸🇳', away: '伊拉克', awayFlag: '🇮🇶', venue: '多伦多', status: 'upcoming', score: null },
    { id: 63, date: '2026-06-27', time: '11:00', timeET: '23:00 ET', group: 'G', home: '埃及', homeFlag: '🇪🇬', away: '伊朗', awayFlag: '🇮🇷', venue: '西雅图', status: 'upcoming', score: null },
    { id: 64, date: '2026-06-27', time: '11:00', timeET: '23:00 ET', group: 'G', home: '新西兰', homeFlag: '🇳🇿', away: '比利时', awayFlag: '🇧🇪', venue: '温哥华', status: 'upcoming', score: null },
    { id: 65, date: '2026-06-27', time: '08:00', timeET: '20:00 ET', group: 'H', home: '佛得角', homeFlag: '🇨🇻', away: '沙特', awayFlag: '🇸🇦', venue: '休斯顿', status: 'upcoming', score: null },
    { id: 66, date: '2026-06-27', time: '08:00', timeET: '20:00 ET', group: 'H', home: '乌拉圭', homeFlag: '🇺🇾', away: '西班牙', awayFlag: '🇪🇸', venue: '瓜达拉哈拉', status: 'upcoming', score: null },
    { id: 67, date: '2026-06-28', time: '05:00', timeET: '17:00 ET', group: 'L', home: '巴拿马', homeFlag: '🇵🇦', away: '英格兰', awayFlag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', venue: '纽约/新泽西', status: 'upcoming', score: null },
    { id: 68, date: '2026-06-28', time: '05:00', timeET: '17:00 ET', group: 'L', home: '克罗地亚', homeFlag: '🇭🇷', away: '加纳', awayFlag: '🇬🇭', venue: '费城', status: 'upcoming', score: null },
    { id: 69, date: '2026-06-28', time: '10:00', timeET: '22:00 ET', group: 'J', home: '阿尔及利亚', homeFlag: '🇩🇿', away: '奥地利', awayFlag: '🇦🇹', venue: '堪萨斯城', status: 'upcoming', score: null },
    { id: 70, date: '2026-06-28', time: '10:00', timeET: '22:00 ET', group: 'J', home: '约旦', homeFlag: '🇯🇴', away: '阿根廷', awayFlag: '🇦🇷', venue: '达拉斯', status: 'upcoming', score: null },
    { id: 71, date: '2026-06-28', time: '07:30', timeET: '19:30 ET', group: 'K', home: '哥伦比亚', homeFlag: '🇨🇴', away: '葡萄牙', awayFlag: '🇵🇹', venue: '迈阿密', status: 'upcoming', score: null },
    { id: 72, date: '2026-06-28', time: '07:30', timeET: '19:30 ET', group: 'K', home: '刚果(金)', homeFlag: '🇨🇩', away: '乌兹别克斯坦', awayFlag: '🇺🇿', venue: '亚特兰大', status: 'upcoming', score: null },
    { id: 73, date: '2026-06-29', time: '03:00', timeET: '15:00 ET', group: 'KO', home: 'A组第二', homeFlag: '⚽', away: 'B组第二', awayFlag: '⚽', venue: '洛杉矶', status: 'upcoming', score: null, stage: '16强' },
    { id: 74, date: '2026-06-30', time: '04:30', timeET: '16:30 ET', group: 'KO', home: 'E组第一', homeFlag: '⚽', away: '最佳第三名', awayFlag: '⚽', venue: '波士顿', status: 'upcoming', score: null, stage: '16强' },
    { id: 75, date: '2026-06-30', time: '09:00', timeET: '21:00 ET', group: 'KO', home: 'F组第一', homeFlag: '⚽', away: 'C组第二', awayFlag: '⚽', venue: '蒙特雷', status: 'upcoming', score: null, stage: '16强' },
    { id: 76, date: '2026-06-30', time: '01:00', timeET: '13:00 ET', group: 'KO', home: 'C组第一', homeFlag: '⚽', away: 'F组第二', awayFlag: '⚽', venue: '休斯顿', status: 'upcoming', score: null, stage: '16强' },
    { id: 77, date: '2026-07-01', time: '05:00', timeET: '17:00 ET', group: 'KO', home: 'I组第一', homeFlag: '⚽', away: '最佳第三名', awayFlag: '⚽', venue: '纽约/新泽西', status: 'upcoming', score: null, stage: '16强' },
    { id: 78, date: '2026-07-01', time: '01:00', timeET: '13:00 ET', group: 'KO', home: 'E组第二', homeFlag: '⚽', away: 'I组第二', awayFlag: '⚽', venue: '达拉斯', status: 'upcoming', score: null, stage: '16强' },
    { id: 79, date: '2026-07-01', time: '09:00', timeET: '21:00 ET', group: 'KO', home: 'A组第一', homeFlag: '⚽', away: '最佳第三名', awayFlag: '⚽', venue: '墨西哥城', status: 'upcoming', score: null, stage: '16强' },
    { id: 80, date: '2026-07-02', time: '00:00', timeET: '12:00 ET', group: 'KO', home: 'L组第一', homeFlag: '⚽', away: '最佳第三名', awayFlag: '⚽', venue: '亚特兰大', status: 'upcoming', score: null, stage: '16强' },
    { id: 81, date: '2026-07-02', time: '08:00', timeET: '20:00 ET', group: 'KO', home: 'D组第一', homeFlag: '⚽', away: '最佳第三名', awayFlag: '⚽', venue: '旧金山湾区', status: 'upcoming', score: null, stage: '16强' },
    { id: 82, date: '2026-07-02', time: '04:00', timeET: '16:00 ET', group: 'KO', home: 'G组第一', homeFlag: '⚽', away: '最佳第三名', awayFlag: '⚽', venue: '西雅图', status: 'upcoming', score: null, stage: '16强' },
    { id: 83, date: '2026-07-03', time: '07:00', timeET: '19:00 ET', group: 'KO', home: 'K组第二', homeFlag: '⚽', away: 'L组第二', awayFlag: '⚽', venue: '多伦多', status: 'upcoming', score: null, stage: '16强' },
    { id: 84, date: '2026-07-03', time: '03:00', timeET: '15:00 ET', group: 'KO', home: 'H组第一', homeFlag: '⚽', away: 'J组第二', awayFlag: '⚽', venue: '洛杉矶', status: 'upcoming', score: null, stage: '16强' },
    { id: 85, date: '2026-07-03', time: '11:00', timeET: '23:00 ET', group: 'KO', home: 'B组第一', homeFlag: '⚽', away: '最佳第三名', awayFlag: '⚽', venue: '温哥华', status: 'upcoming', score: null, stage: '16强' },
    { id: 86, date: '2026-07-04', time: '06:00', timeET: '18:00 ET', group: 'KO', home: 'J组第一', homeFlag: '⚽', away: 'H组第二', awayFlag: '⚽', venue: '迈阿密', status: 'upcoming', score: null, stage: '16强' },
    { id: 87, date: '2026-07-04', time: '09:30', timeET: '21:30 ET', group: 'KO', home: 'K组第一', homeFlag: '⚽', away: '最佳第三名', awayFlag: '⚽', venue: '堪萨斯城', status: 'upcoming', score: null, stage: '16强' },
    { id: 88, date: '2026-07-04', time: '02:00', timeET: '14:00 ET', group: 'KO', home: 'D组第二', homeFlag: '⚽', away: 'G组第二', awayFlag: '⚽', venue: '达拉斯', status: 'upcoming', score: null, stage: '16强' },
    { id: 89, date: '2026-07-05', time: '05:00', timeET: '17:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '费城', status: 'upcoming', score: null, stage: '8强' },
    { id: 90, date: '2026-07-05', time: '01:00', timeET: '13:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '休斯顿', status: 'upcoming', score: null, stage: '8强' },
    { id: 91, date: '2026-07-06', time: '04:00', timeET: '16:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '纽约/新泽西', status: 'upcoming', score: null, stage: '8强' },
    { id: 92, date: '2026-07-06', time: '08:00', timeET: '20:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '墨西哥城', status: 'upcoming', score: null, stage: '8强' },
    { id: 93, date: '2026-07-07', time: '03:00', timeET: '15:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '达拉斯', status: 'upcoming', score: null, stage: '8强' },
    { id: 94, date: '2026-07-07', time: '08:00', timeET: '20:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '西雅图', status: 'upcoming', score: null, stage: '8强' },
    { id: 95, date: '2026-07-08', time: '00:00', timeET: '12:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '亚特兰大', status: 'upcoming', score: null, stage: '8强' },
    { id: 96, date: '2026-07-08', time: '04:00', timeET: '16:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '温哥华', status: 'upcoming', score: null, stage: '8强' },
    { id: 97, date: '2026-07-10', time: '04:00', timeET: '16:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '波士顿', status: 'upcoming', score: null, stage: '四分之一决赛' },
    { id: 98, date: '2026-07-11', time: '03:00', timeET: '15:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '洛杉矶', status: 'upcoming', score: null, stage: '四分之一决赛' },
    { id: 99, date: '2026-07-12', time: '05:00', timeET: '17:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '迈阿密', status: 'upcoming', score: null, stage: '四分之一决赛' },
    { id: 100, date: '2026-07-12', time: '09:00', timeET: '21:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '堪萨斯城', status: 'upcoming', score: null, stage: '四分之一决赛' },
    { id: 101, date: '2026-07-15', time: '03:00', timeET: '15:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '达拉斯', status: 'upcoming', score: null, stage: '半决赛' },
    { id: 102, date: '2026-07-16', time: '03:00', timeET: '15:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '亚特兰大', status: 'upcoming', score: null, stage: '半决赛' },
    { id: 103, date: '2026-07-19', time: '05:00', timeET: '17:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '迈阿密', status: 'upcoming', score: null, stage: '三四名决赛' },
    { id: 104, date: '2026-07-20', time: '03:00', timeET: '15:00 ET', group: 'KO', home: '待定', homeFlag: '⚽', away: '待定', awayFlag: '⚽', venue: '纽约/新泽西', status: 'upcoming', score: null, stage: '决赛' }
  ],
  // 集锦由 highlights.js + fetch-highlights.py 多平台聚合
  highlights: [],

  broadcasters: [
    { name: 'FIFA+', region: '全球', url: 'https://www.fifa.com/fifaplus', logo: '🌐' },
    { name: 'Fox Sports', region: '美国', url: 'https://www.foxsports.com/soccer/fifa-world-cup', logo: '📺' },
    { name: 'CBC', region: '加拿大', url: 'https://www.cbc.ca/sports/soccer', logo: '📡' },
    { name: 'Televisa', region: '墨西哥', url: 'https://www.televisa.com', logo: '📻' },
    { name: '央视体育', region: '中国', url: 'https://sports.cctv.com', logo: '🇨🇳' },
    { name: '咪咕视频', region: '中国', url: 'https://www.miguvideo.com', logo: '📱' },
  ],

  liveMatch: {
    id: 29,
    commentary: [
      { minute: 0, text: '即将开始：巴西 vs 海地，费城林肯金融球场' },
      { minute: 0, text: '巴西队近期状态出色，海地力争爆冷' },
      { minute: 0, text: '预计首发：维尼修斯、拉菲尼亚领衔巴西攻击线' },
    ],
  },
};
